### ISSUE TITLE
提一个小需求，能不能把dock栏图标隐藏掉？

### ISSUE THREAD

**Issue by iblueer** [NeuxLab/cc#1]
这种每天开着的，放到后台的app，老是在dock栏显示图标，有点奇怪。例子就是OneDrive等app提供隐藏dock图标的功能。

**Comment by gockxml** [comment]
@iblueer 感谢建议，我们确实也有这个打算。

其实最开始的设计是没有 dock 图标的，但有的文件不好复制两次（比如 Chrome 里下载的文件），就参考Evernote 加了 dock 图标，这样可以拖拽文件到图标上实现收集。后来，我们实现了唤醒快捷键 Cmd + Option + C，这样就可以拖拽文件时唤醒CC助手直接拖入了，图标就不是特别需要了。

所以，我们会默认不再显示 dock 图标，至于要不要保留显示的选项，还需要再考虑下。应该会在几天内解决并发布更新的。

**Comment by iblueer** [comment]
我刚才测试了一下，cmd opt c 会默认打开 alfred 的一个功能（虽然没用过），cmd ctrl c 才是打开 cc助手。期待你们的更新。

2018/07/12 午後6:15、Gock <notifications@github.com<mailto:notifications@github.com>>のメール:


@iblueer<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fiblueer&data=02%7C01%7C%7C620e3b7efa1a46e28edf08d5e7e06a38%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636669873395840483&sdata=Xc4QsQxvd0Rbd%2FEpB7O2qFunFA4dtuvrHMwDQHAVzlo%3D&reserved=0> 感谢建议，我们确实也有这个打算。

其实最开始的设计是没有 dock 图标的，但有的文件不好复制两次（比如 Chrome 里下载的文件），就参考Evernote 加了 dock 图标，这样可以拖拽文件到图标上实现收集。后来，我们实现了唤醒快捷键 Cmd + Option + C，这样就可以拖拽文件时唤醒CC助手直接拖入了，图标就不是特别需要了。

所以，我们会默认不再显示 dock 图标，至于要不要保留显示的选项，还需要再考虑下。应该会在几天内解决并发布更新的。

**Comment by acenqiu** [comment]
在 1.0.1 版本中已隐藏 dock 栏图标。
