### ISSUE TITLE
英文系统，是否可以使用翻译成英文的插件

### ISSUE THREAD

**Issue by wolfFN** [NeuxLab/cc#17]
电脑：MBP
系统：OSX

插件中只有 “Translate to Chinese”，个人猜测可能是因为系统为英文所致。求助能否有设置处，个人选择想采用的插件。多谢！

**Comment by gockxml** [comment]
感谢反馈。这个是插件多语言的文字失误，应该为 Translate。这个插件会自动监测当前的文本，如果是中文就翻译为英文，如果是英文就自动翻译为中文，所以应该能满足你的需求。

**Comment by acenqiu** [comment]
该问题已修正，将在下个版本中发布。
