### ISSUE TITLE
如果使用snipaste的话，如何实现复制两次

### ISSUE THREAD

**Issue by ych0537** [NeuxLab/cc#19]
windows系统，对应截图软件snipaste。
snipaste选取图片的快递单号之后，点击复制按钮之后截图状态画面就消失，没办法复制两次。
即使使用快速点击两次或者快速按两次Ctrl C 也不能复制到CC助手里。

**Comment by acenqiu** [comment]
你可以在截图后按 Ctrl + Alt + C 激活主窗口，这个时候会自动复制到CC助手里。

**Comment by ych0537** [comment]
实验成功。十分感谢。
