### ISSUE TITLE
试了一下，CC助手和Paste Plain Text有兼容性冲突。

### ISSUE THREAD

**Issue by iblueer** [NeuxLab/cc#3]
在开启Paste Plain Text的情况下，会自动增加一次CtrlC次数，也就是，如果我在CC助手中设置触发次数为2的话，只需要我按1次CtrlC就能触发CC助手；如果我在CC助手中设置触发次数为3的话，只需要我按2次CtrlC就能触发CC助手。

**Comment by gockxml** [comment]
@iblueer 已修复。可能需要点一下检查更新。
